### ISSUE TITLE
Add ability to view green user profiles from user search?

### ISSUE THREAD

**Issue by rgc-exists** [Cvolton/betterinfo-geode#1]
I have an old green user account I made that I am able to find with the user search feature, but I can't view the profile! Just wondering, is it possible to make it so you can view the green user's profile from the user search just like you can from a level page?

PS: I ran a custom script to try and find it and accidentally ratelimited myself, so I obviously am not the one to do this 💀

**Comment by Cvolton** [comment]
unfortunately not possible for 2 reasons
1) user search only returns registered accounts - if an account appears green there, it just means it doesn't have all data generated properly (this likely means it's never been logged into)
2) all "green" users in user search return user ID 0, so it's impossible to identify them
