### ISSUE TITLE
Disable level length for platformer levels

### ISSUE THREAD

**Issue by Bituvo** [Cvolton/betterinfo-geode#17]
See title. Only classic mode levels should display an estimated level length.

**Comment by Cvolton** [comment]
Can add as an option but I don't see an issue with displaying it for platformer levels as well when it's available

**Comment by Cvolton** [comment]
added an option to hide this in 01b1594b8983e545718114b857c4ff685523caa5 as part of the worseinfo initiative

**Comment by Cvolton** [comment]
just stating that this feature is being removed, as showing level length for platformer levels is a vanilla feature now (and it works in the exact same way the betterinfo implementation did)
