### ISSUE TITLE
Demon Filter Not Working

### ISSUE THREAD

**Issue by SuperDasher** [Cvolton/betterinfo-geode#18]
When trying to filter by demon difficulty the mod instead filters by the length.
I don't know why it does it but here's a visual representation of it
![GeometryDash_p5QpLZ6jgm](https://github.com/Cvolton/betterinfo-geode/assets/72823509/0d3efe14-df9d-4894-b106-6099d24b461d)

**Comment by Cvolton** [comment]
fixed in d5ed8da0c8cd3f5033d953bcde591110e92368c4, release scheduled for alpha 14
