### ISSUE TITLE
dependancy error in new update

### ISSUE THREAD

**Issue by adam11111111111111111111121** [Cvolton/betterinfo-geode#25]
![Screenshot_2024-03-25-20-04-50-612_com geode launcher](https://github.com/Cvolton/betterinfo-geode/assets/127667039/2daf126f-b33a-4500-bee1-637757546b73)
my android is 64bit and i have GD ver 2.2.13 and geode ver 1.3.2

**Comment by Cvolton** [comment]
seems to be a bug in geode where it sometimes doesnt detect mods on the index properly, try to install "Misc Bugfixes" mod separately and then install the update

**Comment by Cvolton** [comment]
closing as it is not directly related to BI itself
