### ISSUE TITLE
Inconsistent right-side Saved Levels button layout

### ISSUE THREAD

**Issue by xparadoxical** [Cvolton/betterinfo-geode#26]
1. Open saved levels
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/3922b5b5-a8ad-4e01-9a03-227a857ba905)
2. Switch to favorite lists
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/48a026b4-486f-4fa2-a9f2-c49fae448aa7)
3. Exit the menu and open saved levels again (it's in lists mode)
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/71544719-16d8-44dd-abac-6515b7e962c9)
4. Switch to levels (sets the layout to (1))

**Comment by Cvolton** [comment]
this looks like its partially a vanilla bug as well? because the root of the issue seems to be that the folder button only appears upon reentering the menu (is the button even needed? i cant find a way to set a folder for a list)

**Comment by xparadoxical** [comment]
it is actually a vanilla bug, moving to Misc Bugfixes
