### ISSUE TITLE
Only some of the "go to last page" buttons are hidden on the last page

### ISSUE THREAD

**Issue by xparadoxical** [Cvolton/betterinfo-geode#28]
In daily/weekly/chest history it disappears. Anywhere else it doesn't. It should match the behvior of the << button and of the GD next-page button.

**Comment by xparadoxical** [comment]
on v4.1.8 in map packs it disappears properly but in saved levels and favorite lists it doesn't

**Comment by xparadoxical** [comment]
present in 4.1.9 as described above @Cvolton

**Comment by xparadoxical** [comment]
present in 4.1.10 @Cvolton

**Comment by xparadoxical** [comment]
present in v4.2.0-beta.3 @Cvolton 😭
![GeometryDash_4YaOQQG1HI](https://github.com/Cvolton/betterinfo-geode/assets/43796685/1956671f-6f6a-4b46-b4cb-76d3f955c868)

**Comment by Cvolton** [comment]
The ones that are visible are from the vanilla game hope that helps
