### ISSUE TITLE
Out of bounds pages in favorite lists

### ISSUE THREAD

**Issue by xparadoxical** [Cvolton/betterinfo-geode#29]
The not-sus-looking last page button (2nd one in #27) and the random page button act as if I had 7 pages of favorite lists instead of the actual 4.
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/001ccd87-6ffe-4513-b8b4-dd2e3b9b351d)

**Comment by Cvolton** [comment]
impostor button...

**Comment by xparadoxical** [comment]
still happens on v4.1.8
I had 20 local levels per page enabled when taking the previous screenshots btw.

saved levels with 20/p (doesn't happen with 10/p and stops happening as soon as I delete a level):
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/572676b4-cedc-4348-b2c5-cadec0a13e97)
fav lists with 10/p (doesn't happen with 20/p and stops happening as soon as I unfav a list):
![image](https://github.com/Cvolton/betterinfo-geode/assets/43796685/67c97520-8978-4e03-9aa9-c9c28bb0251b)

**Comment by xparadoxical** [comment]
present in 4.1.9 as described above @Cvolton

**Comment by Cvolton** [comment]
Hm this could be related to why the folder button only shows up sometimes, reopening then

**Comment by Cvolton** [comment]
oh, I see, this is a different but related issue where the page counter can be off by one if every page has max levels
