### ISSUE TITLE
Double clicking the back button on the filters menu in the search menu crashes the game

### ISSUE THREAD

**Issue by scrahe** [Cvolton/betterinfo-geode#3]

**Comment by Cvolton** [comment]
unable to replicate, can you provide a crashlog and/or a more detailed description on how to (preferably consistently) re-create the issue?

**Comment by scrahe** [comment]
If you go into the search menu in GD, then click the plus button and go to the second page, then double click the button to go back a page, the game crashes.

**Comment by scrahe** [comment]
Using this method, I was able to crash the game 5 times in a row.

**Comment by Cvolton** [comment]
can you share a crash log?

**Comment by scrahe** [comment]
[2023-10-13_08-45-37.log](https://github.com/Cvolton/betterinfo-geode/files/12894210/2023-10-13_08-45-37.log)

**Comment by scrahe** [comment]
https://github.com/Cvolton/betterinfo-geode/assets/55860416/9b845694-9c3c-4e7f-b546-90b79d0d77c7

**Comment by Cvolton** [comment]
Thank you for elaborating on the report, I've identified the issue and implemented a fix for the next release
