### ISSUE TITLE
Crashes when searching for a level

### ISSUE THREAD

**Issue by cootshk** [Cvolton/betterinfo-geode#35]
MacOS, M2 Macbook Air

The game crashes when searching for a level 
[Log (username removed for privacy)](https://github.com/Cvolton/betterinfo-geode/files/15344102/2024-05-17_00-37-18.log)
Using just the globed mod works fine

**Comment by Cvolton** [comment]
Appears to be a bug in Node IDs mod, https://github.com/geode-sdk/node-ids/issues would be a more appropriate place to report this then

**Comment by cootshk** [comment]
> Appears to be a bug in Node IDs mod, https://github.com/geode-sdk/node-ids/issues would be a more appropriate place to report this then

404 Repo not found, but the game crashes with only Node IDs so ill report it there
