### ISSUE TITLE
Betterinfo wont show me the upload date

### ISSUE THREAD

**Issue by Ev212** [Cvolton/betterinfo-geode#36]
Noticed recently that when i go to the upload date it just shows as N/A and never change
Is this my problem or something with the mod and how to fix?
<img width="1920" alt="Geometry Dash Screenshot 2024 05 19 - 19 05 10 60" src="https://github.com/Cvolton/betterinfo-geode/assets/78379509/919ff068-37a2-49a8-ae85-eb2f8601feab">

**Comment by Cvolton** [comment]
getting the upload date relies on [GDHistory](https://history.geometrydash.eu/) which was temporarily down because of server provider issues. These were resolved earlier today, so I'm marking the issue as resolved
