### ISSUE TITLE
I cant open the game

### ISSUE THREAD

**Issue by LeMikusito** [Cvolton/betterinfo-geode#39]
After i upsated this mod, i just cannot open the game, directly gives me an issue
[2024-05-25_13-42-11.log](https://github.com/Cvolton/betterinfo-geode/files/15464032/2024-05-25_13-42-11.log)
This has nothing to do with it, but a while ago I had another error, but now with the GDDPintegration mod, I wanted to access the progress packs, and the game crashed, and that didn't happen before I updated it, I don't know if I know It may be due to an error in the mods, the geode, or my unit, but it happens recently that I update a mod, and immediately that mod stops working and I have to disable it or uninstall it outright, I don't know much about these issues, but I might Find out if there is anything that can be done about it. Thank you!

**Comment by LeMikusito** [comment]
The last paragraph had nothing to do with the initial problem, but if you can resolve that question I would be very grateful.

**Comment by Cvolton** [comment]
fixed in 4.1.13
