### ISSUE TITLE
Add a list of followed creators

### ISSUE THREAD

**Issue by xparadoxical** [Cvolton/betterinfo-geode#41]
this isn't displayed in-game, so 1. followed creators can't easily be managed, 2. you don't know how many you're following (helpful when completing the achievement through the pacifist route (so not in 1 minute)), 3. you can't share your follow list with anyone (especially in case you're a stargrinder that's open to publicize their trade secret)

**Comment by Cvolton** [comment]
planned, started work on the feature yesterday

**Comment by Cvolton** [comment]
implemented, will be added in the next update
