### ISSUE TITLE
large daily chests don't appear in chest history

### ISSUE THREAD

**Issue by jauao1** [Cvolton/betterinfo-geode#47]
i've probably opened more than 200 large chests but it doesnt appear in chest history
i always open large and small chest at the same time, no way that i have opened 240 small chests and only 146 large chests
i also tested and it doesnt appear

sorry if i had bad english, i hope you understand

**Comment by Cvolton** [comment]
small chests can be opened more frequently than large chests so from that standpoint alone it would make sense for most people to have more small chests than large chests

the chests are taken from your save file, perhaps you can try cross checking with gdsave and see if that differs https://gdcolon.com/gdsave/

**Comment by Cvolton** [comment]
stale issue, unable to reproduce
