### ISSUE TITLE
Likely bug: Ghost List rewards

### ISSUE THREAD

**Issue by Naxrin** [Cvolton/betterinfo-geode#52]
it says i can claim from 1 list rewards, while i click ok and see nothing there
![image](https://github.com/user-attachments/assets/563783f0-9897-4cc9-abcd-4eb2702660bb)

**Comment by Cvolton** [comment]
Likely a deleted list that was formerly rated? Can you send the Geode log file from a game launch where the popup appears? It should reveal the ID of the list it's trying to download

**Comment by Cvolton** [comment]
added fallback code that partially addresses this issue here e33e2b22272b0df124b75790b61199e083092c67

**Comment by Cvolton** [comment]
further addressed in 3c7650e1e5b373da512b890eac6ae7a0487bea9b, should practically be resolved now
