### ISSUE TITLE
Issue with Main Levels Info

### ISSUE THREAD

**Issue by nbieberitz** [Cvolton/betterinfo-geode#59]
There should be First and Last Played, and Completed Timestamps on BOTH custom levels AND main levels. However, main levels only have Last Played...

![Screenshot_20241122_224455_Geode](https://github.com/user-attachments/assets/2218f2ca-5fa1-4ed0-af63-5fb77b0393f3)

![Screenshot_20241122_224509_Geode](https://github.com/user-attachments/assets/9c0e2d9c-6a4a-4cd2-93c3-9371a9db5905)

**Comment by Cvolton** [comment]
this is because you completed the levels before installing the mod, therefore the timestamp is unavailable

**Comment by nbieberitz** [comment]
Ok
