### ISSUE TITLE
saved levels

### ISSUE THREAD

**Issue by Headphones361** [Cvolton/betterinfo-geode#61]
when i go on to saved levels and i try to Delete a level that i haven't beaten it Doesn't work

https://github.com/user-attachments/assets/0dbcb716-f3a2-498e-8061-529df6542ad5

**Comment by Cvolton** [comment]
this is actually a quirk of how the filter system works - if you change the saved filters, you will see that the level actually did get deleted, you just need to refresh the page

still a valid issue though, will have to fix

**Comment by yesseruser** [comment]
Maybe #66 will be fixed by this as well?

**Comment by Cvolton** [comment]
fixed in 46222abb7acf95a22ec92feb3929f94a644cf838 (scheduled for BI 4.3.3)
