### ISSUE TITLE
[Bug] Saved levels folders don't apply when filters are applied

### ISSUE THREAD

**Issue by yesseruser** [Cvolton/betterinfo-geode#66]
On the saved levels screen, if I have some filters set and I change the folder shown, it doesn't do anything and just shows the filtered levels of the last opened folder before applying the filters.

**Comment by Cvolton** [comment]
fixed in 46222abb7acf95a22ec92feb3929f94a644cf838 (scheduled for BI 4.3.3)

**Comment by yesseruser** [comment]
> fixed in [46222ab](https://github.com/Cvolton/betterinfo-geode/commit/46222abb7acf95a22ec92feb3929f94a644cf838) (scheduled for BI 4.3.3)

Woah that was fast. Thanks!
